version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: tracking-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - tracking-network

  tracking-service:
    build: .
    container_name: tracking-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - SERVER_READ_TIMEOUT=30s
      - SERVER_WRITE_TIMEOUT=30s
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - REDIS_TTL=1h
      - EXTERNAL_API_URL=https://track.4px.com
      - EXTERNAL_API_TIMEOUT=30s
      - EXTERNAL_API_RETRY_COUNT=3
      - BATCH_SIZE=50
      - BATCH_FLUSH_TIMEOUT=2s
      - BATCH_WORKERS=3
      - LOG_LEVEL=info
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - tracking-network

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: tracking-redis-commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    networks:
      - tracking-network
    profiles:
      - tools

volumes:
  redis_data:

networks:
  tracking-network:
    driver: bridge
